### ISSUE TITLE
Is the depth in the dataset metric?

### ISSUE THREAD

**Issue by ZachL1** [lawrence-cj/ARKitTrack#5]
Hi,thank you for your outstanding contribution.
I have a question, is the depth in the dataset in metric?

**Comment by lawrence-cj** [comment]
The original depth is in millimeter and saved as 16bit format in our Dataset. The depth file loading function is at [here](https://github.com/lawrence-cj/ARKitTrack/blob/master/lib/test/evaluation/tracker.py#L299)

**Comment by ZachL1** [comment]
Thanks for your quick reply, I get it. Thanks again!
